#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
zxkbmap de &
picom -f --config $HOME/.config/picom/picom.conf &
sh $HOME/.config/autostart/polybar_init.sh &
sh $HOME/.config/autostart/pywal_init.sh &
nitrogen --restore &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a firefox desktop='^2'
# bspc rule -a discord desktop='^3'
# bspc rule -a spotify desktop='^4'
